# Generated by Django 5.0.6 on 2024-10-07 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bottel', '0008_alter_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Cash on Delivery'), ('UPI', 'UPI')], default=False, max_length=50),
        ),
    ]
