# Generated by Django 5.0.6 on 2024-10-07 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bottel', '0015_order_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
    ]
